블래잭 구현 리뷰 부탁드립니다.
kimtaesoo99/java-blackjack pull request #1
Opened 2023-06-03 10:33 UTC by kimtaesoo99

블랙잭 구현 리뷰 부탁드립니다!

2023-06-04 01:07 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +    private List<Participant> participants;
`List<Participant>`를 관리할 수 있지 않을까?

2023-06-04 01:08 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +        participants.add(new Dealer(new Name(DEALER)));
이 부분에 Participants에 첫 순서를 `Dealer`로 만드려고 의도한 것 같은데
이건 다른 방법도 많긴 한데, 태수야 너가 한 방법을 조금 더 나아지게 하려면 어떻게 해야할까?

위에서 말한 것처럼 일급컬렉션 + 정적 팩토리 메서드로 해결해볼래?

2023-06-04 01:10 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +            Arrays.stream(names).forEach(name -> participants.add(new Player(new Name(name))));
`.forEach()`를 개행하나 추가해주고 쓰면 더 깔끔할듯~

2023-06-04 01:11 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +            String nameInfo = InputView.readParticipantName();
static 메서드로 사용한 이유가 뭐야?

2023-06-04 01:12 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +        });
이것도 `일급 컬렉션`으로 관리할 수 있지 않을까?
그럴 때 장점은 무엇일까?

2023-06-04 01:13 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +        while ((player.canDraw() && command.equals(YES))) {
`(player.canDraw() && command.equals(YES))` 부분을 메서드로 분리해서 의도를 한 눈에 파악할 수 있게 하는 건 어떨까?

2023-06-04 01:15 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +        String command = YES;
`String`이라는 타입 말고 Enum 혹은 다른 객체로 관리했을 때 장점은 무엇일까?

2023-06-04 01:17 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +    private final Cards cards = new Cards();
만약 게임이 두 번 시작할 수 있게 된다면, 카드팩은 첫 게임에 영향을 받을까?

2023-06-04 01:20 UTC, sosow0212 commented on src/main/java/view/InputValidation.java
> +    public static void addMoreCardCommand(String command) {
`!(Yes || NO)`일 때 다시 입력하는 경우니깐
메서드명을 다른 것으로 바꾸는게 좋지 않을까?

2023-06-04 01:20 UTC, sosow0212 commented on src/main/java/view/InputValidation.java
> +            throw new IllegalStateException(COMMAND_ERROR_MESSAGE);
굿굿 시간되면 커스텀 예외로 관리해보자~

2023-06-04 01:22 UTC, sosow0212 commented on src/main/java/view/OutputView.java
> +    public static void printInitCardSetting(final List<Participant> participants) {
`View`를 구현하는 사람은 `Participant`를 알고 있어야할까?

2023-06-04 01:27 UTC, sosow0212 commented on src/main/java/view/OutputView.java
> +    public static void printDealerFirstCard(final Participant dealer) {
이 부분도 그렇고 다른 부분에서도 마찬가지네!

2023-06-04 01:52 UTC, sosow0212 commented on src/main/java/domain/Cards.java
> +    public Cards() {
기본 생성자에서는
`public Card(List<Card> cards)` 이런식으로 받게하고,

`정적 팩토리 메서드`를 이용해서 지금 작성한 로직을 만들어주면 어떨까?

이렇게 했을때 장점은 무엇일까?

2023-06-04 01:52 UTC, sosow0212 commented on src/main/java/domain/Dealer.java
> +public class Dealer extends Participant{
정렬이 안 됐넴 항상 정렬하는 습관 들이기!

2023-06-04 01:52 UTC, sosow0212 commented on src/main/java/domain/Pattern.java
> +            .findFirst().orElseThrow();
1. 객체지향 생활체조 4번 규칙이 뭘까?
2. `FindFirst()`랑 `FindAny()`와 차이점은?
3. `orElseThrow()`가 작동할 일이 있을까?

2023-06-04 01:52 UTC, sosow0212 commented on src/main/java/domain/Referee.java
> +    public String compareSumOfCard(final Participant dealer, final Participant player) {
`Participant`가 달라지면 이 메서드도 달라질까?

2023-06-04 01:52 UTC, sosow0212 commented on src/main/java/domain/Deck.java
> +    }
굿 분기 잘 나눴네
가독성 좋게 for{} 밑에 개행, if{} 밑에 개행 하나씩 추가해주면 좋을듯

2023-06-04 01:52 UTC, sosow0212 commented on src/main/java/domain/Deck.java
> +        return cards.stream().anyMatch(card -> isAceCard(card.getNumber()));
객체지향 생활체조 4번 참고

2023-06-04 01:52 UTC, sosow0212 commented on src/main/java/domain/Number.java
> +        this.name = name;
다른 곳에서는 매개변수에 final을 붙였는데, 여기서는 매개변수에 final을 안 붙인 이유가 있을까?

2023-06-04 01:52 UTC, sosow0212 commented on src/test/java/domain/CardTest.java
> +        Card card = new Card(MATCHING_NUMBER);
`Card`를 계속 생성해주는데, `Test Fixture`를 사용해보면 어떨까?
https://junit.org/junit4/cookbook.html

2023-06-04 01:52 UTC, sosow0212 commented on src/test/java/domain/DealerTest.java
> +        //given
given이 없다면 지워줘도 되지 않을까?

2023-06-04 01:52 UTC, sosow0212 commented on src/test/java/domain/DealerTest.java
> +    public void cannotDraw() {
테스트 이름을 짓는 방법에는 여러가지가 있는데, 찾아보고 너만의 기준을 정하는 건 어떨까?

2023-06-04 01:53 UTC, sosow0212 reviewed
태수 전반적으로 저번 처음 때보다 훨씬 깔끔해졌다 굿굿👍
몇 가지만 확인 한 번 해봐

2023-06-05 11:27 UTC, kimtaesoo99 commented on src/main/java/controller/Controller.java
> +            String nameInfo = InputView.readParticipantName();
input과 output의 경우에 값이 변하지 않고 일정하기 때문에 굳이 매 게임마다 새롭게 생성할필요없이 static으로 사용하는 편이 낫다고 생각하였습니다.

2023-06-05 11:28 UTC, kimtaesoo99 commented on src/main/java/controller/Controller.java
> +            String nameInfo = InputView.readParticipantName();
> static 메서드로 사용한 이유가 뭐야?
input과 output의 경우에 값이 변하지 않고 일정하기 때문에 굳이 매 게임마다 새롭게 생성할필요없이 static으로 사용하는 편이 낫다고 생각하였습니다.

2023-06-05 11:29 UTC, kimtaesoo99 commented on src/main/java/controller/Controller.java
> +        });
> 이것도 `일급 컬렉션`으로 관리할 수 있지 않을까? 그럴 때 장점은 무엇일까?

일급컬렉션을 적용하였는데, 참가자들을 한곳에서 관리할수 있다는 장점이 있었고, 그로인해 컨트롤러의 코드가 간단해졌습니다.

2023-06-05 11:31 UTC, kimtaesoo99 commented on src/main/java/controller/Controller.java
> +        String command = YES;
> `YES`라는 상수도 여러 곳에서 사용되고 있는데, `String`이라는 타입 말고 Enum 혹은 다른 객체로 관리했을 때 장점은 무엇일까?

허용한 가능한 값을 제한할 수 있다는 장점이 있었습니다. 또한 검증에 대한 부분도 해당 Enum에서 할 수 있었습니다.

2023-06-05 11:32 UTC, kimtaesoo99 commented on src/main/java/controller/Controller.java
> +    private final Cards cards = new Cards();
> 만약 게임이 두 번 시작할 수 있게 된다면, 카드팩은 첫 게임에 영향을 받을까?

다시 시작시 카드또한 새롭게 초기화하도록 변경하였습니다. 기존로직의 경우 컨트롤러가 생성시에 초기화가 이루어지기때문에 컨트롤러 자체를 새롭게 만들지 않으면 카드팩이 계속해서 영향을 받았습니다.

2023-06-05 11:34 UTC, kimtaesoo99 commented on src/main/java/view/OutputView.java
> +    public static void printInitCardSetting(final List<Participant> participants) {
> `View`를 구현하는 사람은 `Participant`를 알고 있어야할까?

Dto를 사용하여 필요한 부분만 받아서 사용할 수 있도록 로직을 변경하였습니다. View의 경우 Domain에 의존해도 된다고 생각하였지만, 캡슐화가 깨질수도 있고, 불필요한 데이터가 전달될 수 있다고 생각하여 DTO를 사용하였습니다.

2023-06-05 11:35 UTC, kimtaesoo99 commented on src/main/java/domain/Cards.java
> +    public Cards() {
> 기본 생성자에서는 `public Card(List<Card> cards)` 이런식으로 받게하고,
> 
> `정적 팩토리 메서드`를 이용해서 지금 작성한 로직을 만들어주면 어떨까?
> 
> 이렇게 했을때 장점은 무엇일까?

기존의 기본생성자의 경우 단순히 기본생성자만 보고 어떻게 생성되는지 유추하기 힘들다는 단점이있었습니다. 따라서 매개변수로 List<Card>를 받게하는 생성자 덕분에 테스트를 작성하기 편해졌고, 정적 팩토리 메서드를 사용하니 이름을 통해 카드가 어떻게 만들어질지 유추하기 쉽다는 장점이 있었습니다.

2023-06-05 11:38 UTC, kimtaesoo99 commented on src/main/java/domain/Pattern.java
> +            .findFirst().orElseThrow();
> 1. 객체지향 생활체조 4번 규칙이 뭘까?
> 2. `FindFirst()`랑 `FindAny()`와 차이점은?
> 3. `orElseThrow()`가 작동할 일이 있을까?

1. 한줄에 한 점을 찍는 것입니다. 이는 가독성을 위한 규칙이라 생각됩니다.
2. FindFirst와 FindAny의 경우 병렬로 스트림을 돌릴시 차이가 발생하게됩니다. findFirst의 경우 이름 그대로 가장 앞단의 데이터를 찾게됩니다. FIndAny의 경우 이름 그대로 제일 먼저 발견된것을 반환합니다.
3.  비즈니스 로직만 본다면 실제 예외가 작동하지 않게됩니다. 만약 저 부분이 없다면 Optional을 반환하기때문에 밖에서 다시 검증로직이 필요하게됩니다. 따라서 발생할 일이 없지만 예외처리를 통해 해결하였습니다.

2023-06-05 11:39 UTC, kimtaesoo99 commented on src/main/java/domain/Referee.java
> +    public String compareSumOfCard(final Participant dealer, final Participant player) {
> `Participant`가 달라지면 이 메서드도 달라질까?

당연하게 참가자들을 의존하여 값을 계산해야한다고 생각하였지만, 의존하지 않을수 있다면 의존하지 않는 것이 좋은 설계라고 생각하였습니다. 따라서 매개변수로 합계를 받도록 로직을 수정하였습니다.

2023-06-05 11:45 UTC, kimtaesoo99 commented
질문사항이 있어서 남기게되었습니다.
1. 처음에 딜러와 플레이어를 참여자로 묶기위해서 조합을 사용하려 하였습니다. 하지만 결국 참여자의 로직을 다시 호출하는 메서드가 필요하게 되었고 메서드가 단순 위임이라는 생각이 들었습니다. 또한 is-a가 성립하고 참여자를 추상클래스로 두어 상속받는 편이 낫다고 생각하여 구현하였습니다. 이에 대한 생각이 궁금합니다.

2. enum 타입에서 스트림을 돌릴때 Optional을 반환하기때문에 실제 예외가 발생하지 않지만 orElseThrow를 사용하여 해결하였습니다. 이럴 경우 값을 무조건 반환한다는 확신이 있다면 .get을 사용하는 편이 나을지 궁금합니다.

3. 일급컬렉션을 적용하여 참가자들을 관리하였는데, 이때 플레이어 각각을 꺼내어 사용해야하는 부분이있었습니다. 이를 해결하기 위해 getPlayers를 리턴하도록 하였습니다. 저의 설계문제인지 아니면 이러한 로직이 있어도 괜찮은지에 대한 의문이 들었습니다.

2023-06-05 13:33 UTC, sosow0212 commented on src/main/java/domain/Cards.java
> +    public static Cards createAutoCards() {
정적 팩토리 메서드를 사용하는데, 기본 생성자는 private로 하는 것이 좋지 않을까?

2023-06-05 13:40 UTC, sosow0212 commented on src/main/java/domain/Cards.java
> +    }
```suggestion
    public Cards(final List<Card> cards) {
        this.cards = cards;
    }

    public static Cards createAutoCards() {
        List<Card> cards = makeShuffledCards();
        return new Cards(cards);
    }

    private static List<Card> makeShuffledCards() {
        List<Card> cards = new LinkedList<>();

        for (int number = FIRST_CARD_NUMBER; number < CARD_TOTAL_COUNT; number++) {
            cards.add(Card.createWithMatchNumber(number));
        }

        Collections.shuffle(cards);

        return cards;
    }
```

이런 방식은 어떨까.. ㅎㅎ

더 좋은 방식이 있다면 다르게 바꿔도 되고~

2023-06-05 14:02 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +            .forEach(player -> OutputView.printPlayerCards(toDto(player)));
`toDto(player)`가 player를 어떤 dto로 만든다는 의미일까?
클래스명을 앞에 붙여주면 조금 더 보는 사람이 이해하기 좋지 않을까?

2023-06-05 14:02 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +    private static boolean wantToAddCard(final Participant player, final Command command) {
이건 `Controller`에서만 사용하는데, static 메서드일 필요가 있을까?
메서드명도 조금만 더 고민해보면 좋을 것 같아

2023-06-05 14:02 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +        if (command.getStatus()) {
`getStatus()`가 여기서 의미하는게 뭘까?
네이밍 고민을 해보면 좋을 것 같아

2023-06-05 14:02 UTC, sosow0212 commented on src/main/java/domain/Deck.java
> +        return Collections.unmodifiableList(cards);
방어적 복사 굿

2023-06-05 14:02 UTC, sosow0212 commented on src/main/java/domain/Deck.java
> +    private final List<Card> cards = new ArrayList<>();
`= new ArrayList<>()`와 생성자를 이용해서 초기화 해주는 건 무슨 차이가 있을까?

2023-06-05 14:02 UTC, sosow0212 commented on src/main/java/domain/Participants.java
> +import java.util.*;
https://google.github.io/styleguide/javaguide.html

import에서 와일드카드는 지양하는 게 좋아~

2023-06-05 14:02 UTC, sosow0212 commented on src/main/java/domain/Participants.java
> +    public static Participants createDealerAndPlayers(final Dealer dealer, final List<Participant> players) {
정적 팩토리 메서드를 사용하는 이유가 뭘까?

2023-06-05 14:02 UTC, sosow0212 commented on src/main/java/domain/Participants.java
> +    public Participants(final Dealer dealer, final List<Participant> players) {
1. 기본 생성자의 접근 제어자는 닫아주는게 좋지 않을까?

2. 정적 팩토리 메서드에서 예외처리를 해주고 생성해주는 것과, 생성자에서 예외를 처리해주고 만들어주는 것과 무슨 차이가 있을까?

2023-06-05 14:02 UTC, sosow0212 commented on src/main/java/domain/Participants.java
> +        for (Participant participant : players) {
어떤 건 final이 붙고 어떤 건 안 붙었는데 통일성 있게 해주는게 좋지 않을까?

2023-06-05 14:02 UTC, sosow0212 commented on src/main/java/domain/Participants.java
> +        boolean exist = players.stream()
`exist`는 뭐를 의미하는 변수일까?

2023-06-05 14:02 UTC, sosow0212 commented on src/main/java/domain/Participants.java
> +            .anyMatch(player -> player.getName().equals(DEALER));
`player.getName().equals(DEALER)` 이 역할을 플레이어가 해주는 것이 맞을까?
`Name`이라는 객체로 이름에 대한 것을 원시값 포장을 하고 있는데, `Name`에서 이 로직을 수행해주는 것이 책임에 맞지 않을까?

2023-06-05 14:02 UTC, sosow0212 commented on src/main/java/domain/Participants.java
> +            throw new WrongNameException(NAME_ERROR_MESSAGE);
예외를 보면 지금 `RuntimeException`을 모두 상속받고, super()에 메시지를 넣어주고 있는데, 모든 예외를 그렇게 하고 있는 것 같아. (중복)

이렇게 한 이유가 있을까?

2023-06-05 14:02 UTC, sosow0212 commented on src/main/java/domain/Pattern.java
> +            .findFirst()
`findAny()`로 했을 땐 원하는 결과가 안 나올까?

2023-06-05 14:02 UTC, sosow0212 commented on src/main/java/domain/Name.java
> +public class Name {
`Equals, HashCode 재정의`란 무엇일까?

2023-06-05 14:02 UTC, sosow0212 commented on src/main/java/domain/Referee.java
> +        return false;
```suggestion
return secondSum > BLACK_JACK && firstSum <= BLACK_JACK;
```

이렇게 줄일 수 있을 것 같아~

2023-06-05 14:03 UTC, sosow0212 commented on src/main/java/dto/ParticipantResponseDto.java
> +    private final List<Card> cards;
Dto로 `cards`를 넘겨주는데, View에서 `Card`를 알필요가 있을까?

2023-06-05 14:05 UTC, sosow0212 commented on src/main/java/dto/ParticipantResponseDto.java
> +    public ParticipantResponseDto(List<Card> cards, String name, int sum) {
1. 이 클래스에는 매개변수에 final이 안 붙었는데 의도한 걸까?

2. `ParticipantResponseDto`라는 클래스 네이밍을 보고, sum이 무엇을 의미하는지 어떻게 알까?

2023-06-05 14:07 UTC, sosow0212 commented on src/main/java/view/OutputView.java
> +    private static String sortResult(Map<String, Integer> resultStatus) {
`resultStatus`라는 `Map`자료구조에서 `key, value`가 의미하는 건 각각 뭐고, 이걸 어떻게 알까?

다른 방법으로 줄 수 있는 방법은 없을까?

2023-06-05 14:09 UTC, sosow0212 commented on src/test/java/domain/CommandTest.java
> +class CommandTest {
예외에 대한 테스트는 안 해도 될까?

2023-06-05 14:10 UTC, sosow0212 commented on src/test/java/domain/NameTest.java
> +        Assertions.assertThatThrownBy(() -> new Name(BLANK))
`blank`를 검증할 수 있는 어노테이션이 있는데 함 찾아보기~

2023-06-05 14:12 UTC, sosow0212 commented on src/test/java/domain/ParticipantsTest.java
> +        Assertions.assertThatThrownBy(() -> participants = Participants.createDealerAndPlayers(dealer, players))
이것도 조금 어색한 것 같은데, `Participants` 클래스의 생성 구조때문에 이런 것 같아.
한 번 생성 부분을 고치고, 이것도 바꿔보면 좋을 것 같아

2023-06-05 14:14 UTC, sosow0212 requested changes
태수야 리뷰 확인하고 함 다시 고쳐봐 고생했다

> 처음에 딜러와 플레이어를 참여자로 묶기위해서 조합을 사용하려 하였습니다. 
하지만 결국 참여자의 로직을 다시 호출하는 메서드가 필요하게 되었고 메서드가 단순 위임이라는 생각이 들었습니다. 또한 is-a가 성립하고 참여자를 추상클래스로 두어 상속받는 편이 낫다고 생각하여 구현하였습니다. 이에 대한 생각이 궁금합니다.

- 사실 정답이 없지만, 조합과 상속이라는 키워드를 봤을 때 굉장히 비슷한 느낌이 강해서 그럴 수 있다고 생각하는데,
나는 강한 의존으로 인해 웬만하면 조합을 사용할 것 같아. 하지만 진짜 is-a 관계이고, 변화 가능성이 없다면 상속이 더 나을 수도 ㅎㅎ

> enum 타입에서 스트림을 돌릴때 Optional을 반환하기때문에 실제 예외가 발생하지 않지만 orElseThrow를 사용하여 해결하였습니다. 이럴 경우 값을 무조건 반환한다는 확신이 있다면 .get을 사용하는 편이 나을지 궁금합니다.

- 이건 사실 나도 케바케인 것 같긴한데, 100% 보장을 할 수 있는 경우
ex.  `Optional<...> product = ..` 이런 식으로 옵셔널로 만들고, if문을 통해서 `product.isEmpty()`와 같은 분기를 통해 먼저 null 값인 경우를 처리해주고, 그 다음에 `product`로직을 활용하는 경우는 100% 존재하니깐 (if를 통해 이미 null인지 검증 했기 때문) `.get()`을 사용하는 편이야.
그렇지 않으면 보는 입장에서는 null이 될 수도 있는지 혼란이 올 수 있기 때문이야

> 일급컬렉션을 적용하여 참가자들을 관리하였는데, 이때 플레이어 각각을 꺼내어 사용해야하는 부분이있었습니다. 이를 해결하기 위해 getPlayers를 리턴하도록 하였습니다. 저의 설계문제인지 아니면 이러한 로직이 있어도 괜찮은지에 대한 의문이 들었습니다.

- `validatePlayersName()` 메서드에서 `.anyMatch(player -> player.getName().equals(DEALER));` 이런 것과 같은 부분에서 질문하는 것 같은데 리뷰에도 남겨놨으니 확인해봐~

2023-06-06 13:21 UTC, kimtaesoo99 commented on src/main/java/domain/Deck.java
> +    private final List<Card> cards = new ArrayList<>();
> `= new ArrayList<>()`와 생성자를 이용해서 초기화 해주는 건 무슨 차이가 있을까?

생성자에서 List<Card>를 받아서 초기화해준다면 테스트를 작성하는데 간편하다는 장점이 있습니다.

2023-06-06 13:23 UTC, kimtaesoo99 commented on src/main/java/domain/Participants.java
> +            throw new WrongNameException(NAME_ERROR_MESSAGE);
> 예외를 보면 지금 `RuntimeException`을 모두 상속받고, super()에 메시지를 넣어주고 있는데, 모든 예외를 그렇게 하고 있는 것 같아. (중복)
> 
> 이렇게 한 이유가 있을까?

우선 커스텀예외는 단순하게 이름으로 무엇을 나타내는지를 표현하려고 커스텀 예외를 하였습니다. 
에러 메시지의 경우 출력이 필요한 부분이 있기에 super()를 사용하였습니다.

2023-06-06 13:23 UTC, kimtaesoo99 commented on src/main/java/domain/Pattern.java
> +            .findFirst()
> `findAny()`로 했을 땐 원하는 결과가 안 나올까?

findAny()를 사용하여도 같은 결과가 나오게됩니다. 하지만 만약 병렬로 스트림을 돌린다면 결과가 달라질 수 있습니다.

2023-06-06 13:46 UTC, sosow0212 commented on src/main/java/domain/Deck.java
> +    private int tempAceOfValue(final int sumOfCard) {
`tempAceOfValue`는 뭘 의미하는 걸까?
메서드가 명사로 시작하네

2023-06-06 13:49 UTC, sosow0212 commented on src/main/java/domain/Player.java
> +public class Player extends Participant{
정렬 습관화 하기

2023-06-06 13:49 UTC, sosow0212 commented on src/main/java/domain/Players.java
> +import java.util.*;
import의 와일드카드 지양하기

2023-06-06 13:52 UTC, sosow0212 commented on src/main/java/dto/ParticipantResponseDto.java
> +public class ParticipantResponseDto {
Response라는 의미가 있는데 Dto란 명칭도 같이 붙여준 이유가 있을까?
개인적으로 Response가 Dto의 의미도 포함하고 있다고 생각하는데, 태수야 너는 어떻게 생각해?

2023-06-06 13:52 UTC, sosow0212 commented on src/main/java/view/InputView.java
> +    public static final String INPUT_PLAYERS_NAME = "게임에 참여할 사람의 이름을 입력하세요.(쉼표 기준으로 분리)";
접근제어자가 public인 이유가 있을까?

2023-06-06 13:54 UTC, sosow0212 approved these changes
굿 이정도면 괜찮은듯
추가 코멘트 남긴거 확인해봐 태수야

2023-06-09 05:55 UTC, merged