[refactor] 기능 요구 사항이 변경됨에 따라 전체적인 로직 수정하였습니다.
kimtaesoo99/java-blackjack pull request #2
Opened 2023-06-10 13:49 UTC by kimtaesoo99

리뷰 부탁드립니다.
하면서 들었던 의문에 대해 질문드립니다.
1. 심판이라는 객체를 만들어서 사용하였는데, 전반적으로 유틸기능으로 사용하였습니다. 이때 이를 유틸로 판단되면 static으로 선언하여 사용하는 것은 괜찮은지에 대한 의문이 들었습니다.
2. import의 경우 자동으로 와일드카드로 변환될때가 있는데 이 경우에도 와일드카드를 지우고 하나씩 구체적으로 적어주어야하는지 궁금합니다.
3. Participant에 Amount를 인스턴스 변수로 선언하여 딜러와 플레이어의 코드 중복을 줄이고 싶었습니다. 하지만 Amount의 메서드를 사용하는 것에 있어서 다른 부분이 존재하여 딜러와 플레이어에서도 각각 amount를 호출해야하는 일이 발생하였습니다.  protected로 선언하여 다른 부분만 부모클래스에서 호출하여 수정하는 것이 맞는지, 아니면 중복이 발생하더라도 딜러, 플레이어 각각에 Amount를 선언하는 것이
맞는지 의문이 들었습니다.
4. Participant의 경우 인스턴스 변수로 Name, Deck이 존재합니다. 하지만 생성자의 경우 Name만을 받고, 로직에서 Deck을 new해주었습니다. (Deck의 경우 빈 리스트를 받아야함) 이 경우에 바깥에서 Name만 넣어주면 되기에 깔끔하다고 생각하였습니다.(어차피 밖에서 빈 리스트를 만들고 덱까지 만들어주면 전체적으로 더러워보인다고 판단) 이러한 경우에도 Participant의 생성자 매개변수로 Name, Deck 두개를 받는것이 맞는지에 대한 의문이 들었습니다.

2023-06-11 08:15 UTC, sosow0212 commented on src/main/java/dto/ParticipantResponse.java
> +    public ParticipantResponse(final List<String> cardsName, final String name, final int sumOfCards) {
정적 팩토리 메서드를 사용하는데 private로 닫아주는게 좋지 않을까?

2023-06-11 08:16 UTC, sosow0212 commented on src/main/java/view/InputView.java
>      private static final Scanner scanner = new Scanner(System.in);
한칸 띄어주기

2023-06-11 08:19 UTC, sosow0212 commented on src/main/java/domain/Card.java
>      public static Card createWithMatchNumber(final int matchingNumber) {
굿 잘 바꿨네 태수야
근데 정적 팩토리 메서드가 생성자 아래로 가는게 좋을듯

2023-06-11 08:20 UTC, sosow0212 commented on src/main/java/domain/Dealer.java
> +    private Amount amount;
현재 코드에서는 final로 선언 해줄 수 있는데 안 해준 이유가 있어?

2023-06-11 08:26 UTC, sosow0212 commented on src/main/java/domain/Referee.java
> +    private void distributeLoseCase(final String result, final Player player, final Dealer dealer, final int amount) {
1. 매개변수는 3개까지 (요구 사항)
2. Player, Dealer는 이 클래스에 의존하는 것일까?

2023-06-11 08:27 UTC, sosow0212 commented on src/main/java/domain/Referee.java
> +    private void distributeDrawCase(final String result, final Player player) {
여기도 Player가 바뀌면, Referee 클래스의 기능도 바뀔 수 있지 않을까?
구조를 개선할 수 있을 것 같은데 한 번 해보는 게 어떨까?

2023-06-11 08:28 UTC, sosow0212 commented on src/main/java/dto/DealerAmountResponse.java
> +    public DealerAmountResponse(String name, int betAmount) {
1. 정적 팩토리 메서드를 사용하는데 접근제어자를 열어준 이유가 있어?
2. 다른 부분은 메서드 파라미터를 모두 final을 붙이는데, 여기선 안 한 이유가 있을까?

2023-06-11 08:29 UTC, sosow0212 commented on src/main/java/dto/DealerAmountResponse.java
> +    public static DealerAmountResponse toDto(final Dealer dealer) {
메서드 순서 맞춰주기

보통 순서대로 메서드를 나열해주고 get/setter는 맨 아래로 내리고, 그 밑에 Equals HashCode 같은 걸 해주는 편이야

2023-06-11 08:31 UTC, sosow0212 commented on src/test/java/domain/AmountTest.java
> +class AmountTest {
예외는 처리 안해줘도 될까?
꼼꼼한 테스트를 하는게 좋을듯

2023-06-11 08:34 UTC, sosow0212 commented on src/main/java/domain/Player.java
> +public class Player extends Participant {
`Players` 클래스 import 와일드 카드도 지워줘

2023-06-11 08:34 UTC, sosow0212 requested changes
굿굿 많이 좋아졌네 태수야 리뷰 남긴거 확인해보고 고쳐봐
처음보다 코드도 훨 깔끔해지고 많이 좋아졌네 

의존하는 객체가 있는데, 최대한 의존하지 않도록 리팩토링을 해보는 게 좋을 것 같아

> 1. 심판이라는 객체를 만들어서 사용하였는데, 전반적으로 유틸기능으로 사용하였습니다. 이때 이를 유틸로 판단되면 static으로 선언하여 사용하는 것 은 괜찮은지에 대한 의문이 들었습니다.

- 일단 해당 클래스는 지금까지 스프링하면서 만든 Service Layer 느낌으로 사용하는 것 같은데, 의존 문제부터 리팩토링 해보는 게 좋을 것 같아. 그리고 유틸을 static으로 사용할 순 있지만, 해당 클래스의 기능들을 static으로 바꿔서 유틸로 사용하면 어떤 문제점이 있을까?
장단점 모두 있다고 생각하는데, 개인적으로 나는 유틸로 빼는 기능들은 많은 클래스에서 공통적으로 사용하는 기능들 (예를 들면 매핑의 역할 혹은 파싱해주는 것들)을 유틸로 빼는 편이야

> 2. import의 경우 자동으로 와일드카드로 변환될때가 있는데 이 경우에도 와일드카드를 지우고 하나씩 구체적으로 적어주어야하는지 궁금합니다.

- 인텔리제이에서 기억하기로 5개가 해당 패키지에 있으면 자동으로 와일드카드로 바꾸는데, 이건 설정에서 바꿔줄 수 있어
나는 그래서 999개로 바꿔서 와일드카드가 안나오게끔 변경 했어.

> 3. Participant에 Amount를 인스턴스 변수로 선언하여 딜러와 플레이어의 코드 중복을 줄이고 싶었습니다. 하지만 Amount의 메서드를 사용하는 것에 있어서 다른 부분이 존재하여 딜러와 플레이어에서도 각각 amount를 호출해야하는 일이 발생하였습니다. protected로 선언하여 다른 부분만 부모클래스에서 호출하여 수정하는 것이 맞는지, 아니면 중복이 발생하더라도 딜러, 플레이어 각각에 Amount를 선언하는 것이
맞는지 의문이 들었습니다.

- 해당 클래스는 질문을 했기 때문에 리뷰를 남기진 않았는데, 문제가 있어 보이긴 해
인터페이스를 만들어서 최대한 구조를 유연하게 바꿔보면 어떨까? 인터페이스로 구조를 변경했을 때 질문하는 부분에 해당하는 문제점을 해소할 수 있을 것 같아

인터페이스로 어느 정도 뺀 후에, 개별적으로 관리를 하는게 좋을 것 같다고 생각들어
지금 구조에서는 Amount에서 일부 기능은 player가 사용하고 일부는 dealer가 사용하니깐~

> Participant의 경우 인스턴스 변수로 Name, Deck이 존재합니다. 하지만 생성자의 경우 Name만을 받고, 로직에서 Deck을 new해주었습니다. (Deck의 경우 빈 리스트를 받아야함) 이 경우에 바깥에서 Name만 넣어주면 되기에 깔끔하다고 생각하였습니다.(어차피 밖에서 빈 리스트를 만들고 덱까지 만들어주면 전체적으로 더러워보인다고 판단) 이러한 경우에도 Participant의 생성자 매개변수로 Name, Deck 두개를 받는것이 맞는지에 대한 의문이 들었습니다.

- 도메인이 변경되지 않는다면 지금 방식대로 해도 문제가 없겠지만, 나는 개인적으로 이럴 때 정적 팩토리 메서드를 많이 활용해주고 있긴해 생성자는 기본 파라미터만 받게끔 만들고, 정적 팩토리 메서드로 뭐 예를 들면 `createDefaultParticpant(final Name name)`이런 네이밍으로 만들어줄 것 같아.

이렇게 했을 땐, `Participant`를 생성하는 전략이 추가로 생겼을 때에도 유연하게 기본 생성자를 이용해서 정적 팩토리 메서드로 생성 메서드를 만들어 줄 수 있기 때문이야

2023-06-17 10:29 UTC, kimtaesoo99 commented
리뷰 부탁드립니다.
또한 진행하면서 들었던 의문에 대한 질문을 올립니다.

1. participant에 대해 인터페이스로 구현해볼까에 대해 생각해봤습니다. 인터페이스로 둘 경우 장점은 공통메서드를 묶어서 사용가능합니다. 인스턴스변수가 구현체에 정의되기때문에 바로 로직을 구현할 수 있습니다. 하지만 중복 로직이 있는 경우 구현체에서 같은 부분을 동시에 구현해야합니다. 추상클래스의 경우에 단점은 player와 dealer에서 사용되는 메서드의 차이가 있기에 participant를 구현할때 사용하지 않는 메서드가 생기게된다는 것입니다. 또한 상속받은 클래스의 내부를 알아야한다는 단점도 존재하였습니다. 하지만 중복 코드를 확실하게 줄일 수 있다고 생각했습니다. 둘다 장단점이 명확하여 고민을 하였습니다. 이 과정에서 인스턴스변수를 protected로 선언하면 추상클래스를 사용하여도 사용하지않는 메서드가 생기는 것을 막을 수 있다는 장점이 있었습니다. 단점으로는 같은 패키지 내에서 해당 인스턴스변수에 접근할 수 있다는 단점이 생기게되어 고민을 하였습니다. 즉 캡슐화에 문제가 생긴다는 것입니다. 하지만 제가 내린 결론은 도메인 패키지와 자식클래스 내에서만 접근이 가능하기에 실질적으로 접근하지는 않을 것이라 판단하였습니다. 따라서 protected를 사용하여 구현하였습니다. 또한 패키지를 따로 묶을까에 대해서도 고민을 하였지만, 이렇게까지는 진행하지 않았습니다. 이러한 구현에 대한 의견이 궁금합니다.

2. 상금을 분배하는 과정 즉 distributeRevenue 메서드가 원래는 Referee에 있었습니다. 사실 이 부분은 서비스 로직에 있어도 된다고 판단하여 컨트롤러로 로직을 이동하였습니다. 이 과정에서 의문점이 들었습니다. 첫번째는 상금을 분배하는 과정이 결국 player와 dealer의 메서드를 호출해야하는 과정이 있습니다. 즉 의존이 생길수 밖에 없다고 판단하였습니다. 만약 Referee에 있다면 이러한 의존이 불가피하다는 생각이 들었는데, 이러한 의존은 발생해도 된다고 생각했는데 그래도 다른 방법으로 수정해야하는지 궁금해졌습니다. 현재 컨트롤러가 조금 커진 느낌이 있는데 서비스 로직으로 따로 분리하는 것이 나을지도 궁금합니다. (어느 정도가 컨트롤러로써 적당한 크기인지)

2023-06-17 14:17 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +            Dealer dealer = Dealer.create(new Account(new Name(DEALER), new Amount(INIT_AMOUNT)));
Dealer를 생성되는게 도메인의 역할 중 하나라면
Dealer.createDefault() 같은 걸로하고 나머지는 숨겨버리는 것이 나을 수도 있어보이네요
Controller에서 DEALER의 이름과 INIT_AMOUNT의 값을 알 필요가 있을까요?

2023-06-17 14:26 UTC, sosow0212 commented on src/main/java/dto/DealerAmountResponse.java
> +public class DealerAmountResponse {
`PlayerAmountResponse`랑 똑같은 역할이지?
근데 Player와 Dealer와 같은 부모, 같은 역할을 하는데 차라리 하나로 통일을 하고 이름을 ParticipantAmountResponse로 바꾸는 것을 어떨까

2023-06-17 14:27 UTC, sosow0212 approved these changes
굿굿 태수 처음보다 엄청 좋아졌네
남긴 코멘트 확인하고, 추가적으로는 다음 레벨 진행하면서 코멘트 할게
여기서 머지합니다잉

---

리뷰 부탁드립니다.
또한 진행하면서 들었던 의문에 대한 질문을 올립니다.

1. participant에 대해 인터페이스로 구현해볼까에 대해 생각해봤습니다. 인터페이스로 둘 경우 장점은 공통메서드를 묶어서 사용가능합니다. 인스턴스변수가 구현체에 정의되기때문에 바로 로직을 구현할 수 있습니다. 하지만 중복 로직이 있는 경우 구현체에서 같은 부분을 동시에 구현해야합니다. 추상클래스의 경우에 단점은 player와 dealer에서 사용되는 메서드의 차이가 있기에 participant를 구현할때 사용하지 않는 메서드가 생기게된다는 것입니다. 또한 상속받은 클래스의 내부를 알아야한다는 단점도 존재하였습니다. 하지만 중복 코드를 확실하게 줄일 수 있다고 생각했습니다. 둘다 장단점이 명확하여 고민을 하였습니다. 이 과정에서 인스턴스변수를 protected로 선언하면 추상클래스를 사용하여도 사용하지않는 메서드가 생기는 것을 막을 수 있다는 장점이 있었습니다. 단점으로는 같은 패키지 내에서 해당 인스턴스변수에 접근할 수 있다는 단점이 생기게되어 고민을 하였습니다. 즉 캡슐화에 문제가 생긴다는 것입니다. 하지만 제가 내린 결론은 도메인 패키지와 자식클래스 내에서만 접근이 가능하기에 실질적으로 접근하지는 않을 것이라 판단하였습니다. 따라서 protected를 사용하여 구현하였습니다. 또한 패키지를 따로 묶을까에 대해서도 고민을 하였지만, 이렇게까지는 진행하지 않았습니다. 이러한 구현에 대한 의견이 궁금합니다.

> 사실 protected 접근 제어자를 사용해서 막는 것도 하나의 방법이지만, 나는 별로 선호 안 하는 것 같아.
이번에 상속이랑 인터페이스 둘 다 사용해보니깐 느꼈겠지만, 나는 개인적으로 상속은 강한 결합이 생기기 때문에 잘 사용하지는 않는 편이야. (물론 확실한 그런 관계이면 사용하겠지만, 실제로 확실한 관계여도 바뀔 수 있기 때문에, 그런 경우 리팩토링 비용이 크기 때문에 잘 안 사용하긴 해)
구현도 구현마다 케바케지만, 지금처럼 구현한 경우에 protected로 한 경우 필요없는 접근은 막을 수는 있겠지만, 더 좋은 방법이 있기 때문에, 나쁜 방법은 아니지만 더 좋은 차선책이 있다! 라고 말해주고 싶어

2.  상금을 분배하는 과정 즉 distributeRevenue 메서드가 원래는 Referee에 있었습니다. 사실 이 부분은 서비스 로직에 있어도 된다고 판단하여 컨트롤러로 로직을 이동하였습니다. 이 과정에서 의문점이 들었습니다. 첫번째는 상금을 분배하는 과정이 결국 player와 dealer의 메서드를 호출해야하는 과정이 있습니다. 즉 의존이 생길수 밖에 없다고 판단하였습니다. 만약 Referee에 있다면 이러한 의존이 불가피하다는 생각이 들었는데, 이러한 의존은 발생해도 된다고 생각했는데 그래도 다른 방법으로 수정해야하는지 궁금해졌습니다. 현재 컨트롤러가 조금 커진 느낌이 있는데 서비스 로직으로 따로 분리하는 것이 나을지도 궁금합니다. (어느 정도가 컨트롤러로써 적당한 크기인지)

> 음 도메인끼리 연결을 해주는 과정은 불가피하고 그런 부분을 지금은 MVC패턴으로 진행하기에 컨트롤러로 해준 것 같은데,
도메인 또한 복잡해진다면 컨트롤러도 복잡해지겠지? 나는 개인적으로 서비스 레이어를 두어서 작은 컨트롤러의 역할로 사용해도 좋을 것 같아
객체에게 메시지를 보내기 위해서 서비스가 사용자의 메시지를 받고 판단해서 각 도메인에게 메시지를 보내서 해결하는 것이지.
컨트롤러로써 적당한 크기는 사실 이것도 사람마다 많이 달라서 어떤게 "적당하다 좋다"라고 말할 수는 없을 것 같은데, 내 기준으로는 도메인이 지금처럼 복잡해지고, `계산 => 참여자, 딜러 계산`, `카드 뽑기 => 참여자, 딜러`와 같이 기능들이 많아지거나, `도메인으로써 역할이 너무 복잡해지는 경우` 이런 경우 나눌 것 같아.

2023-06-17 14:28 UTC, sosow0212 approved these changes
굿굿 태수 처음보다 엄청 좋아졌네
남긴 코멘트 확인하고, 추가적으로는 다음 레벨 진행하면서 코멘트 할게
여기서 머지합니다잉

2023-06-20 09:00 UTC, merged